CAST_OPTIONS = {
    "options": [
        "Aarakh","Abdul","Ablakaror","Achagar","Achari","Achary","Acharya","Ad-Dharmi","Adi Dravida","Adiandra","Adidravida","Adikarnataka","Adiwasi",
        "Aentelur","Agamudiyar","Aganarw","Agarawal","Agasa","Aguri","Ahir","Ailceej","Akamudayar","Alial","Ambalaar","Ambalam","Ambattan","Ambiga",
        "Ammalam","Ansari","Anvil Brahmin","Arayan","Archagar","Archakulu","Arora","Arundudhi","Arunthathi","Aryakashtriya","Aryavysya","Asadulu",
        "Asari","Ashur","Athidravida","Atit Bayaji","Ayyar","Baaraju","Babariya","Badai","Badhai","Badhei","Badigar","Bagdi","Bagri","Bairagi",
        "Baishnoi","Baisnab","Baistamba","Bajakas","Bajaniya","Bajantri","Bajir","Bakshi","Bakshi Panch","Balagiga","Baligar","Balija","Balmiki",
        "Baman","Bandaram","Bangali","Banik","Baniya","Banjara","Banniyar","Bannsa","Banwari","Baori","Baphan","Barbar","Barber","Barhai","Bari",
        "Barik","Bashor","Bauliya","Bauri","Bavaji","Bavasar","Bavasarkshatriya","Bawa","Bawaji","Bawaria","Bayar","Bayen","Bazigar","Bedar","Behna",
        "Belavva","Beldar","Benayat","Berad","Bestha","Bhaina","Bhajantri","Bhajir","Bhakta","Bhanbhuniya","Bhand","Bhandari","Bhangi","Bhanushali",
        "Bhar","Bharbhooja","Bharud","Bharvad","Bhat","Bhatera","Bhatti","Bhil","Bhila La","Bhilala","Bhisti","Bhoep","Bhoi","Bhoru","Bhovi","Bhujwa",
        "Bhumihar","Bhumija","Bhurji","Bhuyan","Biar","Billava","Binjwar","Bishnoi","Bohra","Bondil","Bothula","Boya","Brahaman","Brahamin","Brahiman",
        "Brahman","Brahmbhatt","Brahmin","Braji","Brhaman","Brhamin","Brijbasinat","Budabukkala","Buddha","Bukava","Bunkar","Burud","Camsula","Catholic",
        "Chakala","Chakali","Chake","Chakkiliyan","Chamar","Chambhar","Chanthi","Chasa","Chenchu","Cheruman","Chettiar","Chettiyar","Chetty","Chhimbe",
        "Chhipi","Chippa","Choudhari","Choudhary","Christian","Chunara","Chutor","Cugayat","Curavan","Dafali","Danatar","Danbasi","Darbar","Darji","Das",
        "Dasaru","DasnamI Vawa","Davar","Devangashetty","Devara","Devipujak","Dewasi","Dhakar","Dhali","Dhanak","Dhangar","Dhanka","Dhanuk","Dhanwar",
        "Dharkar","Dhimar","Dhiwar","Dhoba","Dhobi","Dhodia Patel","Dhoka","Dholi","Dhuniya","Dhurwa","Dobi","Dom","Dombari","Dommara","Dora","Dosandhi",
        "Dravida","Dube","Dulia","Duluvar","Duma","Dusad","Dusadh","Dushad","Dwar","Dweepara","Ediga","Edris","Ekaradorabiddalu","Ekili","Elakula","Elems",
        "Ezhava","Ezhuthachan","Fakir","Faqir","Fishers","G.S.B","Gadaria","Gadariya","Gadhavi","Gadialohar","Galiara","Gamit","Ganak","Ganda","Gandali",
        "Gandha","Gandharahik","Gandla","Gandrap","Gangemata","Gangtredhu","Ganiga","Ganiger","Garai","Garoda","Garua","Gaud","Gaur","Gavali","Gawariya",
        "Ghachha","Ghachi","Ghantora","Ghasi","Ghatwal","Ghukha","Ghumair","Ghusuria","Girui","Goai","Godali","Gohil","Gokha","Golkar","Gond","Gonday",
        "Gondhali","Gonga","Gopal","Gori","Gosai","Goswami","Goti","Gounder","Gour","Govind","Gowala","Gowari","Gowda","Goyal","Gudia","Gujar","Gujara",
        "Gujjar","Gujjar(Muslim)","Gund","Gupthan","Gurav","Gurjar","Hadi","Hairua","Hajam","Halakki","Halpati","Halwai","Hanabar","Hanber","Harer",
        "Hari","Harijan","Helawar","Hembram","Hindu","Hindu Halpati","Hindu Kumbhar","Hindukrubi","Hindulingayat","Holar","Holaya","Holer","Holeya",
        "Holi","Hussain","Idiga","Igola","Iliger","Iyer","Iyyar","Jacobite","Jadeja","Jaga","Jain","Jaiswal","Jambuli","Jangam","Janwakar","Jat",
        "Jat Sikh","Jatsikh","Jele","Jheemar","Jhinwar","Jingar","Jogi","Julaha","Ka Yasth","Kabbou","Kabirpanthi","Kachhi","Kadanpatadar","Kadulu",
        "Kadwa","Kahar","Kahtiyal","Kaibarta","Kaikadi","Kakhera","Kalal","Kalali","Kalar","Kalaria","Kalasali","Kalbeliya","Kali","Kaligullu","Kallar",
        "Kalu","Kalwar","Kama","Kamar","Kamasala","Kambar","Kamlu","Kamma","Kammalar","Kammara","Kanabar","Kanakkan","Kandera","Kandu","Kanhar",
        "Kantlli","Kanwar","Kapu","Kapuvelama","Karan","Karara","Karmakar","Karnam","Karunegar","Karvi","Kashaty","Kashyap","Kathlik","Kauvnder",
        "Kavunis","Kawar","Kayasth","Kayastha","Kayunllu","Kehsavrajan","Kela","Keshavrajput","Kever","Kewat","Khadia","Khalifa","Khan","Khandelwal",
        "Khandu","Kharwar","Khati","Khatik","Khatri","Khodi","Kihatayera","Kisrubar","Knanaya","Koeri","Kohali","Kohli","Koibartr","Kol","Kolam",
        "Kolar","Kolhu","Koli","Kollan","Kolli","Kolwar","Komati","Kommari","Konar","Kongu Vellala","Koppalavelama","Kopplavelama","Kora","Korama",
        "Koravan","Koravaru","Korawar","Kori","Korku","Korma","Koronga","Koshtha","Koshti","Kotal","Kotvaliya","Kouda","Koya","Krishnanvagai","Kristan",
        "Kshatriya","Kud","Kudumbi","Kulavar","Kulhaiya","Kulubar","Kumar","Kumbara","Kumbaran","Kumbhar","Kumbi","Kumhar","Kummara","Kumrar","Kumuti",
        "Kunbi","Kuppalavelama","Kuraba","Kurava","Kurichian","Kurmi","Kuruba","Kurumbar","Kusavar","Kushwaha","Labbari","Lakha","Lakhara","Lakhera",
        "Laman","Lambani","Lappa","Lappee","Lebbai","Lillai","Lingayat","Lodh","Lodhi","Lohana","Lohar","Luniya","Maatauppar","Madarlu","Madat",
        "Madduala","Madevashashetty","Madhivala","Madiga","Madivala","Madivalashetty","Madivili","Madiwal","Mahabrahman","Mahaishya","Mahajan","Mahali",
        "Mahar","Maharana","Maher","Maheshwari","Mahiyavanshi","Maidukavara","Maisurba","Maithare","Maiya Darbar","Majhi","Makvana","Mala","Malagar",
        "Malakar","Maldhari","Maleyali","Malgar","Mali","Malik","Mallah","Malo","Malwana","Mana","Mandal","Mandi","Mandiga","Mandula","Mang","Mangala",
        "Mangali","Mangia","Manihar","Mankar","Mannadiyar","Mannan","Manne","Mansur","Mansuri","Manyakaran","Mappilla","Mapthan","Marahovi","Marar",
        "Maratha","Maravar","Maraya","Marivala","Marthoma","Maruthuvar","Marve","Marwadi","Mary","Maryali","Mashim","Massey","Matang","Mavadi","Mavi",
        "Mayka","Mayra","Mazabi","Mazhabi","Medar","Meena","Meenavar","Mehar","Mehra","Mehtar","Meo","Mer","Mete","Methar","Miniramanu","Mirasi",
        "Mirza","Mistri","Mochi","Modak","Modugu","Moira","Momin","Mominansari","Mondi","Moopar","Moopnar","Moosari","Moothan","Mothaliar","Mran",
        "Mubbanar","Mudali","Mudaliya R","Mudaliyar","Mudi","Muellu","Mughal","Munda","Muniya","Muppan","Muppar","Murmu","Musahar","Mushar","Muslim",
        "Muslimdarji","Muslimdhobi","Muslimgujar","Muslimhalwai","Muslimlohar","Muslimnai","Muslimrajput","Muslimsalmani","Muslimteli","Muthiriar",
        "Muthrasi","Muthunarayana","Nadar","Nadavar","Nagarchi","Nagvamsham","Nai","Naicker","Naidu","Naik","Naikar","Nainera","Nair","Namasudra",
        "Nambudhiri","Namdari","Namdev","Napit","Nat","Nath","Nathjogi","Natiar","Navi","Navithar","Nayak","Nayaka","Nayanakbhirya",
        "Nayanakshathriyyan","Nayankshatriya","Naybrahmanulu","Naynakishthraja","Nepal","Nese","Nhavi","Nilgar","Nishad","Nodi","Nomosudra",
        "Noprthaona","Nuber","Nuniya","Ochra Brahmin","Od","Oddar","Odde","Oram","Oraon","Orthodox","Others","Paanan","Padmasali","Pagani","Palaeikri",
        "Palaya","Palegara","Palikapu","Paliya","Palle","Panchal","Pandaram","Pandithar","Pandya","Pangaram","Panickar","Paniyan","Para Vannan",
        "Paramanik","Paravan","Parayan","Pardesi","Pardhi","Pardi","Parit","Parjiyat","Parmar","Parsi","Pasi","Patel","Pathan","Patidar","Patil",
        "Patkar","Patni","Patthar","Patwa","Pawar","Pentacostal","Perkunna","Petti","Phanka","Pillai","Pillamer","Pingari","Piniyar","Pinjar","Pinjara",
        "Pisharodi","Poojari","Powar","Pradhan","Prajapat","Pujari","Pujeri","Pulayan","Puri","Pushpakan","Rabari","Rabbari","Rabidas","Raisikh",
        "Rajaka","Rajakulu","Rajaliar","Rajasthani","Rajbanshi","Rajbhar","Rajput","Rajulu","Rajvanshi","Rajwar","Rakithar","Ralliya","Rama","Ramgrhia",
        "Rammalar","Ramoshi","Rana","Ranghar","Rangrej","Ranther","Rao","Raouther","Rathod","Rathwa","Raval","Rawani","Rawhar","Reddiyar","Reddy",
        "Relli","Rewari","Roman","Romancatholik","Routher","S.Siddaru","Sabiriya","Sadgope","Sadh","Sadhu","Saha","Sahara","Sahu","Saifi","Saini",
        "Sainibrahman","Saiyed","Sakala","Sakli","Sali","Salilu","Salivahana","Salvi","Sama","Samagar","Samar","Samdigya","Samma","Sanghar","Sanghi",
        "Sansi","Santhal","Santhali","Sarabandu","Saragara","Sarbjar","Sardar","Sarnakar","Saryan","Sasui","Sathawara","Satyam","Savarkar","Sayed",
        "Segu","Seruai","Setiyar","Setti","Shadi","Shaikh","Shawrastra","Sheetbarjen","Sheikh","Sheshwadi","Shetty","Shikaghar","Shimpi","Shipai",
        "Shoda","Shuthar","Siddiqui","Siddri","Sikh","Sindhi","Sirian","Sirvi","Sohata","Solanki","Soleya","Sonar","Soni","Soren","Srimani","Stat",
        "Sudhi","Sudigadusiddha","Sugali","Sunagar","Sunar","Sundi","Sunni","Sunri","Suphra","Suri","Sutar","Suthar","Swamyagol","Swarnkar","Swnagar",
        "Syrian","Tadvi","Tailor","Talari","Taldada","Tamar","Tamboli","Tamilivas","Tamilu","Tank","Tanti","Tantubai","Tarkhan","Tatwa","Telagamamdelu",
        "Telakula","Teli","Telugu","Teluku","Tentkalu","Thakarda","Thakur","Thandan","Tharakan","Thathera","Thattan","Thaysigar","Thevar","Thikodi",
        "Thiya","Thiyya","Tholiya","Tili","Togata","Tomar","Tuntubai","Turha","Turi","Uddar","Ugrakshtriya","Uppara","Va Irangi Bawa","Vaddaru","Vaddi",
        "Vadi","Vadukana Ikar","Vadukkar","Vaghari","Vaghela","Vaishya","Vaisnav","Valan","Valayar","Vallalar","Valmiki","Vanad","Vanakar","Vanan",
        "Vanand","Vanandvas","Vanar","Vangam","Vani","Vania","Vanican","Vaniyar","Varduka","Varmakar","Varriyar","Vddar","Vedava","Veduvar","Veershiv",
        "Velama","Velan","Vellalar","Verma","Vikanasa","Villiamudu","Visali","Visalu","Vishnu","Vishwakarma","Viswabrahaman","Vokkaliga","Vora","Vyash",
        "Vysya","Vyyulu","Wadar","Waddar","Wadeyar","Wadhi","Waghri","Walikar","Wami","Wathi","Xasxa","Yadav","Yadavar","Yalama","Yalavala","Yanadi",
        "Yeava","Yellu","Yerkula","Yerukala","Yerukula","Yishas","Yrakither"
    ],
    "visible": 8
}
